FROM node:18-alpine AS frontend
WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

CMD ["npm", "run", "dev", "--", "--host"]


FROM python:3.13-alpine AS backend
WORKDIR /app

COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

CMD ["flask", "run", "--host=0.0.0.0"]